---
- hosts: target_servers
  tasks:
    - name: Pull the latest Docker image
      docker_image:
        name: your_docker_image
        source: pull

    - name: Stop existing container
      docker_container:
        name: your_container_name
        state: stopped
        force_kill: yes
      ignore_errors: yes

    - name: Start new container
      docker_container:
        name: your_container_name
        image: your_docker_image
        state: started
