---
- name: Deploy Docker Container
  hosts: target_servers
  tasks:
    - name: Pull the latest Docker image
      docker_image:
        name: myapp:latest
        source: pull
    - name: Stop existing container (if any)
      docker_container:
        name: myapp_container
        state: stopped
    - name: Start new container
      docker_container:
        name: myapp_container
        image: myapp:latest
        state: started
