# deploy_private_docker_image.yml

---
- name: Deploy Private Docker Image
  hosts: target_servers
  become: yes
  tasks:
    - name: Authenticate with Docker Hub (or your private registry)
      docker_login:
        username: mrunalsh
        password: your_docker_token
        registry_url: https://registry.hub.docker.com  # Replace with your registry URL

    - name: Pull the Docker image
      docker_image:
        name: python-app-todo:latest
        source: pull

    - name: Stop existing containers based on the same image
      docker_container:
        name: my-container
        image: python-app-todo
        state: stopped
      ignore_errors: yes  # Ignore errors if no existing container is found

    - name: Start a new container
      docker_container:
        name: my-container
        image: python-app-todo:latest
        ports:
          - "8080:80"  # Example port mapping
        state: started

# Add other necessary tasks (e.g., setting environment variables, volumes, etc.)

